# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c8ccb974cd79dc806b909e80c6bbc6aa8bd933688c846c9f96d479eaf4a2aeb31dcefa25b803a04a01459b6ed4c2dc5909b01f89a96cc77d5c9acc9a8f8147c

test:
  secret_key_base: 44fd02bfbc56450fe0c15d72aff5bc4fec7d59dc045af4e2b09da17a856d7ff418cb83ef8aafa10154ef1fd6a3f03d1ce36ac4c4318387d547e18caa4987a326

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
